#!/bin/bash

set -e -u -x

SERVER_HOST=${1:-"localhost"}
SERVER_PORT=${2:-"4064"}

maprsrcpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# create virtualenv
virtualenv $HOME/omerovenv --system-site-packages
set +u
source $HOME/omerovenv/bin/activate
set -u

# instal OMERO.web prerequisites
pip install -r $HOME/OmeroPy/share/web/requirements-py27-nginx.txt

# install mapr
pip install -e ${maprsrcpath}
$HOME/OmeroPy/bin/omero config set omero.web.apps '["omero_mapr"]'
$HOME/OmeroPy/bin/omero config set omero.web.server_list '[["'${SERVER_HOST}'", '${SERVER_PORT}', "'${SERVER_HOST}'"]]'

# prepare ice.config
sed -i "s/^\(omero\.host\s*=\s*\).*\$/\1$SERVER_HOST/" $HOME/OmeroPy/etc/ice.config
sed -i "s/^\(omero\.port\s*=\s*\).*\$/\1$SERVER_PORT/" $HOME/OmeroPy/etc/ice.config

# setup paths to OMERO.py
export PYTHONPATH=$HOME/OmeroPy/lib/python:$HOME/OmeroPy/lib/python/omeroweb:${PYTHONPATH:-}
export ICE_CONFIG=$HOME/OmeroPy/etc/ice.config

until $HOME/OmeroPy/bin/omero login -s $SERVER_HOST -p $SERVER_PORT -u root -w omero ; do
    >&2 echo "OMERO.server is unavailable - sleeping"
    sleep 10
done

# run tests
(cd ${maprsrcpath} && python setup.py test)

#deactivate
